#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d         

bspc config border_width          2
bspc config window_gap            9
bspc config focused_border_color  "#c5c8c6"
bspc config normal_border_color   "#444444"
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a Gimp-2.10 desktop='^8' state=floating follow=on
bspc rule -a jetbrains-rider desktop='^7' state=floating follow=on
bspc rule -a Brave-browser desktop='^4' follow=on
bspc rule -a firefox desktop='^4' follow=on
bspc rule -a Zathura state=tiled
bspc rule -a discord desktop='^6' follow=on
bspc rule -a Blueman-manager state=floating
bspc rule -a QNapi state=floating
bspc rule -a Qalculate-gtk state=floating
bspc rule -a Thunderbird desktop='^6' follow=on
bspc rule -a obs desktop='^8' follow=on state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Nitrogen state=floating
bspc rule -a Xfce4-power-manager-settings state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a BleachBit state=floating
bspc rule -a Pavucontrol state=floating
# bspc rule -a Sxiv state=floating

#autostart
xrdb -load ~/.Xresources
xsetroot -cursor_name left_ptr
xset r rate 180 35
$HOME/.config/polybar/launch.sh
xwallpaper --zoom /home/kub/pix/wallpapers/1654557456348.jpg &
start-pulseaudio-x11 &
batsignal -b -e &
xidlehook --not-when-audio --not-when-fullscreen --timer 1200 'systemctl suspend' '' &
pgrep bspswallow || bspswallow &
